language: node_js
node_js:
  - "node"
script:
  - yarn test
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
branches:
  only:
    - master
cache:
  yarn: true
  directories:
  - node_modules
addons:
  code_climate:
    repo_token: 